#!/bin/bash

function setup_aliases {
  alias ls='ls -G'
  alias ll='ls -l'
  alias lal='ls -al'
  # safe move
  alias mv='mv -i'
  alias vi='vim'
  alias lsdu='du -sm `ls -a|grep -v "^\.$"|grep -v "^\.\.$"`|sort -n -k1'
}

reset_prompt() {
  PROMPT_COMMAND=""
  unset PS_GIT
}

setup_prompt() {
  # set a fancy prompt (non-color, unless we know we "want" color)
  case "$TERM" in
      xterm-color) color_prompt=yes;;
      xterm-256color) color_prompt=yes;;
  esac

  # uncomment for a colored prompt, if the terminal has the capability; turned
  # off by default to not distract the user: the focus in a terminal window
  # should be on the output of commands, not on the prompt
  # For Xquartz - it supports color but show the TERM as 'xterm' only.
  force_color_prompt=yes

  if [ -n "$force_color_prompt" ]; then
      if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    color_prompt=yes
      else
    color_prompt=
      fi
  fi

  # See man bash /PROMPTING for reference on special sequences
  # For color codes see https://en.wikipedia.org/wiki/ANSI_escape_code
  # Also, .config/config-git/git-aware-prompt/colors.sh
  # config-git module sets the PROMPT_COMMAND and PS_GIT*

  if [ "$color_prompt" = yes ]; then
      #PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
      PS1='\
${debian_chroot:+($debian_chroot)}\
\[\e[1;32m\]\h\
\[\e[0m\]:\
\[\e[1;34m\]\w'\
$PS_GIT\
'\[\e[0m\]\$ '
  else
      #PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
      PS1='${debian_chroot:+($debian_chroot)}\h:\w$PS_GIT\$ '
  fi
  unset color_prompt force_color_prompt

  # If this is an xterm set the title
  case "$TERM" in
  xterm*|rxvt*)
      # user@host:dir
      #PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
      # host:dir
      PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\h: \w\a\]$PS1"
      ;;
  *)
      ;;
  esac
}

function setup_history_params () {
  # don't put duplicate lines or lines starting with space in the history.
  # See bash(1) for more options
  HISTCONTROL=ignoreboth

  # append to the history file, don't overwrite it
  shopt -s histappend

  # for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
  HISTSIZE=1000
  HISTFILESIZE=2000

  # check the window size after each command and, if necessary,
  # update the values of LINES and COLUMNS.
  shopt -s checkwinsize
}

function default_prompt() {
  reset_prompt
  setup_prompt
}

setup_aliases        ; unset setup_aliases
setup_history_params ; unset setup_history_params
default_prompt # call this to set the prompt without the git stuff
