#!/bin/bash

setup_stack_bash() {
  # Haskell stack shell tab completion
  if test -d "${STACK_ROOT}"
  then
    type stack >/dev/null 2>&1 && eval "$(stack --bash-completion-script "$(which stack)")"
  fi
}

setup_stack_bash; unset setup_stack_bash
