#!/bin/bash

# Override any previous PATH settings to make sourcing of this file as an
# idempotent operation. Every new login shell starts with a fresh config.

export LC_ALL=C.UTF-8
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=~/.local/bin:$PATH
export PATH=$PATH:~/.cabal/bin

# IMPORTANT: this is required for binaries like ghc-mod to work without using
# stack-exec especially for invoking them from vim.

# Note: stack appends to the user PATH therefore we have assign here instead of
# an append. Make sure we do not clear the path in case stack has not been
# setup yet.

STACKPATH=`stack path --bin-path`
if test -n "$STACKPATH"
then
  export PATH=$STACKPATH
fi

export GHC_PACKAGE_PATH=`stack path --ghc-package-path`
export HOST_VOL_PATH=/vol/hosts/${HOSTNAME%.*}
